#!/usr/bin/env node
/**
 * km-init.mjs — scaffold a runnable Kotlin Multiplatform app from `templates/kmp-project`.
 *
 * Deterministic and token-free: bytes are moved by the OS, nothing is generated by a
 * model. The template is a complete KMP app (core/{common,data,designsystem} + composeApp
 * + androidApp + iosApp) with no feature modules; the first feature is created later by
 * `kmp-create-feature`.
 *
 *   kmp-ai-kit new GithubLeaderboard com.example.demo
 *   npm run init -- Atlas com.acme.atlas              # from the kit root
 *   node scripts/scaffold/km-init.mjs Atlas com.acme.atlas
 *
 * Also wires the project for the kit: `.kmp.json`, a local copy of the architecture
 * checker (`shared/scripts/kmp_check.py`) and rules, an `opencode.json` that points at
 * this kit's skills/plugin, the KMP subagents, and an initialized `openspec/`.
 *
 * Mirrors KMPilot's `scripts/rename.sh` substitution semantics so a scaffolded project
 * compiles: Compose Multiplatform derives its generated `Res` package from
 * `rootProject.name.lowercase()`, sanitized to a Kotlin identifier, so that import has to
 * move with the project name.
 */

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs"
import { execFileSync } from "node:child_process"
import { basename, dirname, join, relative, resolve, sep } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = resolve(fileURLToPath(new URL("../..", import.meta.url)))
const TEMPLATE = join(ROOT, "templates/kmp-project")

// The template's own identity. `templates/kmp-project` is authored under these names and
// every scaffold rewrites them to the user's. Keep OLD_APP_NS/OLD_APP_ID correct or the
// app module's namespace and applicationId will not land where the sources expect.
const TEMPLATE_IDENTITY = {
  name: "KmpApp",
  pkg: "dev.kmpapp",
  appNs: "dev.kmpapp",
  appId: "dev.kmpapp",
}

const TEXT_EXT = new Set([
  ".kt", ".kts", ".xml", ".gradle", ".pro", ".swift", ".plist", ".pbxproj", ".xcconfig", ".toml", ".properties", ".json", ".md",
])
const SKIP_DIRS = new Set([".git", ".gradle", "build", ".kotlin", ".idea", "Pods", "node_modules", ".kmp"])

const argv = process.argv.slice(2)
const arg = (name, dflt) => {
  const i = argv.indexOf(name)
  return i >= 0 && argv[i + 1] ? argv[i + 1] : dflt
}
const has = (name) => argv.includes(name)

// Positional form is the ergonomic one: `kmp-init <Name> <com.pkg> [dest]`.
// `--name/--pkg/--dest` remain supported and take precedence when given.
const VALUE_FLAGS = new Set(["--dest", "--name", "--pkg"])
const positionals = []
for (let i = 0; i < argv.length; i++) {
  if (VALUE_FLAGS.has(argv[i])) { i++; continue }
  if (argv[i].startsWith("-")) continue
  positionals.push(argv[i])
}
// Tolerate the subcommand form when this script is invoked directly
// (`node km-init.mjs new Atlas com.acme.atlas`) rather than through the CLI.
if (positionals[0] === "new" || positionals[0] === "init") positionals.shift()

const dest = arg("--dest") || positionals[2]
const name = arg("--name") || positionals[0]
const pkg = arg("--pkg") || positionals[1]
const dryRun = has("--dry-run")
// OpenSpec is core to the pipeline, so initializing it is the default;
// `--no-openspec` opts out.
const withOpenspec = !has("--no-openspec")
// Self-contained by default: the project carries its own copy of the kit runtime and
// references no path outside itself, so it stays valid when moved, cloned, or shared.
// `--linked` opts into thin relative links to the kit instead (one source of truth,
// but the project and the kit must move together).
const linked = has("--linked")
const noGit = has("--no-git")
const normalize = has("--normalize")

// `--normalize` is a maintenance mode for the kit itself: it rewrites the vendored
// template from its source identity to TEMPLATE_IDENTITY. Run it after refreshing
// templates/kmp-project from upstream, never as part of a user scaffold.
if (normalize) {
  const SOURCE_IDENTITY = { name: "KMPilot", pkg: "thisissadeghi", appNs: "thisissadeghi.kmpilot", appId: "com.thisissadeghi.kmpilot" }
  const n = renameTree(TEMPLATE, SOURCE_IDENTITY, TEMPLATE_IDENTITY)
  process.stdout.write(`normalized ${TEMPLATE}\n  ${n} files rewritten ${JSON.stringify(SOURCE_IDENTITY)} → ${JSON.stringify(TEMPLATE_IDENTITY)}\n`)
  process.exit(0)
}

if (!name || !pkg) {
  console.error(
    "usage: kmp-init <Name> <com.acme.app> [dest]\n" +
    "       kmp-init --name <Name> --pkg <com.acme.app> [--dest <dir>]\n" +
    "\n" +
    "  <Name>   project name, PascalCase (e.g. Atlas)\n" +
    "  <pkg>    package prefix, lowercase dotted (e.g. com.acme.atlas)\n" +
    "  [dest]   destination directory (default: next to the kit, i.e. <kit>/../<Name>)\n" +
    "\n" +
    "flags: --linked  --dry-run  --force  --no-openspec  --no-git  --normalize",
  )
  process.exit(2)
}
if (!/^[A-Za-z][A-Za-z0-9_.-]*$/.test(name)) {
  console.error("error: project name must start with a letter and contain only letters, digits, '_', '.' or '-'")
  process.exit(2)
}
if (!/^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)+$/.test(pkg)) {
  console.error("error: package must be lowercase dotted with at least two segments, e.g. com.acme.app")
  process.exit(2)
}
// No destination given → create the app next to the kit (the kit lives in the projects
// directory, so this is the intuitive default regardless of where npm invoked us from).
// Pass a destination to put it anywhere else.
const destAbs = resolve(dest || join(ROOT, "..", name))
if (destAbs === ROOT || destAbs.startsWith(ROOT + sep)) {
  console.error(`error: the destination must be outside the kit (got ${destAbs}; kit is ${ROOT})`)
  process.exit(2)
}
if (existsSync(destAbs) && readdirSync(destAbs).length > 0 && !has("--force")) {
  console.error(`error: ${destAbs} exists and is not empty (pass --force to scaffold into it)`)
  process.exit(2)
}

const nameLower = name.toLowerCase().replace(/[^a-z0-9_]/g, "_")
const pkgPath = pkg.replace(/\./g, "/")

/** All files under `dir`, skipping build/VCS dirs. */
function walkFiles(dir, out = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(e.name)) continue
    const p = join(dir, e.name)
    if (e.isDirectory()) walkFiles(p, out)
    else out.push(p)
  }
  return out
}

/** Every directory under `dir` (post-order not needed; callers filter). */
function walkDirs(dir, out = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(e.name)) continue
    const p = join(dir, e.name)
    if (e.isDirectory()) {
      out.push(p)
      walkDirs(p, out)
    }
  }
  return out
}

/**
 * Rewrite the template's identifiers to the project's across every text file, then move
 * the `kotlin/<pkg>/…` directories and flatten the redundant project-name level.
 * Two-phase (OLD → sentinel → NEW) so a NEW value containing an OLD value as a substring
 * is not re-matched and doubled. Order is most-specific-first.
 */
function renameTree(root, from, to) {
  const id = from
  const pairs = [
    [id.appId, "@@KIT_APPID@@"],
    [id.appNs, "@@KIT_APPNS@@"],
    [id.pkg, "@@KIT_PKG@@"],
  ]
  const lower = (s) => s.toLowerCase().replace(/[^a-z0-9_]/g, "_")
  const fromLower = id.name.toLowerCase()
  const toLower = lower(to.name)
  const toPath = to.pkg.replace(/\./g, "/")

  let touched = 0
  for (const file of walkFiles(root)) {
    if (!TEXT_EXT.has(fileExt(file))) continue
    let text = readFileSync(file, "utf8")
    const before = text
    for (const [old, sentinel] of pairs) text = text.split(old).join(sentinel)
    for (const [, sentinel] of pairs) text = text.split(sentinel).join(to.pkg)
    text = text.split(id.name).join(to.name)
    text = text.split(`${fromLower}.`).join(`${toLower}.`)
    if (text !== before) {
      writeFileSync(file, text)
      touched++
    }
  }

  // Move `*/kotlin/<old-pkg-path>` → `*/kotlin/<new-pkg-path>`. The old path may be
  // multi-segment (`dev/kmpapp`), so the destination is anchored at the `kotlin/` root,
  // never at the old dir's immediate parent.
  const fromPath = id.pkg.replace(/\./g, "/")
  const suffix = `/kotlin/${fromPath}`
  for (const dir of walkDirs(root)) {
    const posix = dir.split(sep).join("/")
    if (!posix.endsWith(suffix)) continue
    const kotlinRoot = dir.slice(0, dir.length - suffix.length)
    const target = join(kotlinRoot, "kotlin", toPath)
    if (existsSync(target)) continue
    const tmpParent = join(kotlinRoot, "kotlin")
    const tmp = join(tmpParent, `.km-init.${process.pid}`)
    mkdirSync(tmp, { recursive: true })
    renameSync(dir, join(tmp, "pkg"))
    mkdirSync(dirname(target), { recursive: true })
    renameSync(join(tmp, "pkg"), target)
    rmSync(tmp, { recursive: true, force: true })
    // Prune the old path's now-empty ancestors, stopping at `kotlin/`.
    let p = dirname(dir)
    while (p !== tmpParent && readdirSync(p).length === 0) {
      const next = dirname(p)
      rmSync(p, { recursive: true, force: true })
      p = next
    }
  }

  // Flatten `*/kotlin/<new-pkg-path>/<old-name-lower>` — modules whose namespace was
  // `<pkg>.<name>` now sit one level too deep.
  const flatSuffix = `/kotlin/${toPath}/${fromLower}`
  for (const dir of walkDirs(root)) {
    if (!dir.split(sep).join("/").endsWith(flatSuffix)) continue
    const parent = dirname(dir)
    for (const e of readdirSync(dir)) renameSync(join(dir, e), join(parent, e))
    rmSync(dir, { recursive: true, force: true })
  }

  return touched
}

function fileExt(p) {
  const b = basename(p)
  const i = b.lastIndexOf(".")
  return i < 0 ? "" : b.slice(i).toLowerCase()
}

/**
 * `opencode.json` for the new project.
 *
 * Linked (default): reference the kit with *relative* paths, so the project and the kit
 * stay movable together — an absolute path would pin the project to one machine and
 * break the moment the kit moves or the project is shared. Skills, rules and the guard
 * then keep a single source of truth in the kit, and a kit update reaches every project
 * at once.
 *
 * Vendored: the project carries its own copies under `skills/`, `shared/` and
 * `policies/`, so it is fully self-contained and safe to clone/share on its own —
 * at the cost of no longer tracking the kit.
 */
function opencodeJson(vendored) {
  if (vendored) {
    // Fully local: nothing points outside the project, so it survives a move or a clone.
    return JSON.stringify(
      {
        $schema: "https://opencode.ai/config.json",
        instructions: ["AGENTS.md"],
        skills: { paths: ["skills"] },
        references: {
          "kmp-kit": {
            path: "shared",
            description: "KMP architecture rules (kmp-patterns.md), the deterministic checker, and the state contract",
          },
        },
      },
      null,
      2,
    ) + "\n"
  }
  const kit = relToKit(destAbs)
  const p = (sub) => (kit === "." ? sub : `${kit}/${sub}`)
  return JSON.stringify(
    {
      $schema: "https://opencode.ai/config.json",
      instructions: [p("AGENTS.md")],
      skills: { paths: [p("skills")] },
      plugin: [p(".opencode/plugins/protect-feature.ts")],
      references: {
        "kmp-kit": {
          path: p("shared"),
          description: "KMP architecture rules (kmp-patterns.md), the deterministic checker, and the state contract",
        },
      },
    },
    null,
    2,
  ) + "\n"
}

/**
 * Path from the project to the kit, for the linked `opencode.json`.
 *
 * Both sides are resolved through `realpathSync` first: a purely lexical `relative()`
 * produces a path that does not resolve when either side is reached through a symlink
 * (macOS `/tmp` → `/private/tmp`, a symlinked home, a symlinked projects dir), which
 * silently breaks skill discovery.
 */
function relToKit(fromDir) {
  const real = (p) => {
    try {
      return realpathSync(p)
    } catch {
      return p
    }
  }
  return relative(real(fromDir), real(ROOT)).split(sep).join("/") || "."
}

/**
 * Copy the kit runtime a project needs to stand alone: skills, the shared doctrine and
 * checker, policies, prompts, workflows, docs, the instruction layer, and the guard.
 *
 * `kmp-init` is dropped: it scaffolds *new* apps from the kit's `templates/`, which has no
 * meaning inside an app, and its own path references would dangle here. Its route is
 * removed from the copied router and routing table so nothing points at a missing skill.
 */
function vendorKit(dest) {
  for (const dir of ["skills", "shared", "policies", "prompts", "workflows", "docs"]) {
    cpSync(join(ROOT, dir), join(dest, dir), { recursive: true, force: true })
  }
  rmSync(join(dest, "skills/kmp-init"), { recursive: true, force: true })
  stripKitOnlyRoutes(join(dest, "skills/kmp-router/SKILL.md"))
  stripKitOnlyRoutes(join(dest, "workflows/kmp-routing/pipeline.json"))
  cpSync(join(ROOT, "AGENTS.md"), join(dest, "AGENTS.md"))
  stripKitOnlyInstructions(join(dest, "AGENTS.md"))
  mkdirSync(join(dest, ".opencode/plugins"), { recursive: true })
  cpSync(join(ROOT, ".opencode/plugins/protect-feature.ts"), join(dest, ".opencode/plugins/protect-feature.ts"))
}

/**
 * Remove the app-scaffolding instructions from a copied AGENTS.md. `kmp-init` and its
 * template exist only in the kit; a self-contained app must not instruct its agent to run
 * a command or read a template it does not have.
 */
function stripKitOnlyInstructions(file) {
  if (!existsSync(file)) return
  const out = readFileSync(file, "utf8")
    .replace(/`kmp-init`,\n\s*/, "")
    .replace(/- \*\*A new app comes from `kmp-init`[\s\S]*?visual intent from Penpot\.\n/, "")
    .replace(/\n{3,}/g, "\n\n")
  writeFileSync(file, out)
}

/**
 * Remove the `kmp-init` route from a copied routing file. That skill only exists in the
 * kit, so a self-contained project must not document a route to it. Markdown: drop the
 * table row and the paragraph explaining the new-app-vs-new-feature check. JSON: drop the
 * route object targeting it.
 */
function stripKitOnlyRoutes(file) {
  if (!existsSync(file)) return
  const text = readFileSync(file, "utf8")
  if (file.endsWith(".json")) {
    const parsed = JSON.parse(text)
    if (Array.isArray(parsed.routes)) {
      parsed.routes = parsed.routes.filter((r) => !String(r.target).endsWith(":kmp-init"))
    }
    writeFileSync(file, JSON.stringify(parsed, null, 2) + "\n")
    return
  }
  const out = text
    .replace(/^\|.*`kmp-init`.*\|\s*$/gm, "")
    .replace(/"New app" vs\. "new feature"[\s\S]*?it is `kmp-init`\.\n?/g, "")
    .replace(/\n{3,}/g, "\n\n")
  writeFileSync(file, out)
}

/** `git init` + one initial commit. Skipped when git is absent or identity is unset. */
function gitInit(dest) {
  try {
    try {
      execFileSync("git", ["init", "-b", "main"], { cwd: dest, stdio: "pipe" })
    } catch {
      execFileSync("git", ["init"], { cwd: dest, stdio: "pipe" })
      try {
        execFileSync("git", ["symbolic-ref", "HEAD", "refs/heads/main"], { cwd: dest, stdio: "pipe" })
      } catch { /* leave the default branch name */ }
    }
    execFileSync("git", ["add", "-A"], { cwd: dest, stdio: "pipe" })
    try {
      execFileSync("git", ["commit", "-q", "-m", "Initial commit from KMP AI Kit"], { cwd: dest, stdio: "pipe" })
      return "initialized + committed"
    } catch {
      // Usually an unset user.name/user.email. The files are staged; the user commits.
      return "initialized (staged; set git user.name/email, then commit)"
    }
  } catch {
    return "skipped (git not available)"
  }
}

// ── run ─────────────────────────────────────────────────────────────────────

if (dryRun) {
  const count = walkFiles(TEMPLATE).length
  console.log(JSON.stringify({
    ok: true, dryRun: true, template: TEMPLATE, dest: destAbs, name, pkg,
    files: count, openspec: withOpenspec ? "would initialize" : "skipped",
    note: "would copy the template, rewrite its identifiers, and wire the kit",
  }, null, 2))
  process.exit(0)
}

process.stdout.write(`scaffolding ${name} (${pkg}) → ${destAbs}\n`)
mkdirSync(destAbs, { recursive: true })
cpSync(TEMPLATE, destAbs, { recursive: true, force: true })

const rewritten = renameTree(destAbs, TEMPLATE_IDENTITY, { name, pkg })

// Optional project config (the skills read `appModule` from it; the default is composeApp).
writeFileSync(join(destAbs, ".kmp.json"), JSON.stringify({ appModule: "composeApp" }, null, 2) + "\n")

// The project always carries the checker (so `./gradlew archTest` and CI work with no
// kit) plus the architecture rules it mechanizes. In vendored mode the whole runtime
// comes along; in linked mode these two files are the project-local copy.
mkdirSync(join(destAbs, "shared/scripts"), { recursive: true })
cpSync(join(ROOT, "shared/scripts/kmp_check.py"), join(destAbs, "shared/scripts/kmp_check.py"))
cpSync(join(ROOT, "shared/kmp-patterns.md"), join(destAbs, "shared/kmp-patterns.md"))

// Subagents are always copied: opencode only discovers agents inside the project.
mkdirSync(join(destAbs, ".opencode/agent"), { recursive: true })
for (const f of readdirSync(join(ROOT, ".opencode/agent"))) {
  cpSync(join(ROOT, ".opencode/agent", f), join(destAbs, ".opencode/agent", f))
}

// Vendored mode: bring the skills, rules, policies, AGENTS.md and the guard plugin in,
// so the project is self-contained and safe to clone or share on its own.
if (!linked) vendorKit(destAbs)

writeFileSync(join(destAbs, "opencode.json"), opencodeJson(!linked))

// Runtime artifacts (run ledger, checker report) are tooling output.
const gi = join(destAbs, ".gitignore")
if (existsSync(gi) && !readFileSync(gi, "utf8").includes(".kmp/")) {
  writeFileSync(gi, readFileSync(gi, "utf8").replace(/\s*$/, "\n") + ".kmp/\n")
}

let openspecRan = false
if (withOpenspec) {
  try {
    execFileSync("openspec", ["init", "--tools", "opencode", "--no-animation"], { cwd: destAbs, stdio: "pipe" })
    openspecRan = true
    // Replace OpenSpec's generic project config with the kit's KMP-aware one: the
    // planning artifacts should carry the build layer's context and per-artifact rules.
    cpSync(join(ROOT, "openspec/config.yaml"), join(destAbs, "openspec/config.yaml"))
  } catch (e) {
    console.error(`note: could not run \`openspec init\` (${String(e.message).split("\n")[0]}). Run it yourself in ${destAbs}.`)
  }
}

const gitState = noGit ? "skipped (--no-git)" : gitInit(destAbs)

const fileCount = walkFiles(destAbs).length
const openspecState = openspecRan
  ? "initialized"
  : withOpenspec
    ? "NOT initialized — run `openspec init --tools opencode`"
    : "skipped (--no-openspec)"
process.stdout.write(
  `\ndone — ${fileCount} files, ${rewritten} rewritten\n` +
  `  project : ${destAbs}\n` +
  `  name    : ${name}\n` +
  `  package : ${pkg}\n` +
  `  opencode: ${linked ? `linked (kit at ${relToKit(destAbs)})` : "self-contained (all files copied)"}\n` +
  `  openspec: ${openspecState}\n` +
  `  git     : ${gitState}\n` +
  `\nnext\n` +
  `  1. /opsx-propose                    write the first change's spec\n` +
  `  2. /kmp-create-feature              build the feature in Kotlin\n` +
  `  3. ./gradlew archTest               architecture gate\n`,
)
